let state={csrf:"",apps:[],github:{}};const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const titles={overview:"Portfolio overview",brief:"Capacitor-ready brief",apps:"Apps & suites",listing:"Store listing",credentials:"Store access",automation:"Update delivery",builds:"Builds & output",guide:"Approval guide"};
const storeFields=['locale','app_title','apple_subtitle','google_short_description','full_description','apple_keywords','promotional_text','release_notes','marketing_url','primary_category','secondary_category','copyright','contact_email','contact_phone','target_audience','age_rating_notes','marketing_notes','review_notes','review_contact_first_name','review_contact_last_name','compliance_notes','requires_login','allows_account_creation','contains_ads','uses_tracking','collects_personal_data','shares_personal_data','uses_encryption','user_generated_content','children_targeted','regulated_features','apple_account_email','google_account_email','apple_bundle_registered','apple_app_record_created','google_app_record_created','play_app_signing_enabled','apple_privacy_confirmed','google_data_safety_confirmed','store_agreements_active','update_mode','appflow_app_id','appflow_channel','android_production_rollout','support_url','privacy_url','account_deletion_url'];
function busy(on){$("#busy").hidden=!on}function toast(message,error=false){const el=$("#toast");el.textContent=message;el.className=error?"show error":"show";setTimeout(()=>el.className="",4200)}
async function api(url,options={}){options.headers={...(options.headers||{}),"X-Factory-CSRF":state.csrf};const response=await fetch(url,options);const data=await response.json();if(!response.ok||data.ok===false)throw new Error(data.error||"Request failed");return data}
function go(panel){$$('.panel').forEach(x=>x.classList.toggle('active',x.id===`panel-${panel}`));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.panel===panel));$('#page-title').textContent=titles[panel];scrollTo({top:0,behavior:'smooth'})}
function readiness(app){const relevant=app.checks.filter(x=>x.level!=="MANUAL"&&x.level!=="INFO");if(!relevant.length)return 0;return Math.round(100*relevant.filter(x=>x.level==="PASS").length/relevant.length)}
function appCard(app){const ready=readiness(app);return `<article class="app-card"><div class="app-card-top"><div><p>${escapeHtml(app.suite)} · ${escapeHtml(app.app_role)}</p><h4>${escapeHtml(app.native.display_name)}</h4></div><span class="badge">${escapeHtml(app.native.runner)}</span></div><p>${escapeHtml(app.native.ios_bundle_id)}</p><p>${escapeHtml(app.source.repo)}</p><div class="progress"><i style="width:${ready}%"></i></div><div class="card-foot"><span>${ready}% configured</span><button class="text-button edit-app" data-slug="${escapeHtml(app.slug)}">Edit →</button></div></article>`}
function escapeHtml(value){return String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function optionList(selected=""){return state.apps.map(a=>`<option value="${escapeHtml(a.slug)}" ${a.slug===selected?'selected':''}>${escapeHtml(a.native.display_name)} · ${escapeHtml(a.app_role)}</option>`).join("")}
function render(){const apps=state.apps;$('#metric-apps').textContent=apps.length;$('#metric-suites').textContent=new Set(apps.map(a=>a.suite)).size;$('#metric-ready').textContent=apps.length?`${Math.round(apps.reduce((n,a)=>n+readiness(a),0)/apps.length)}%`:'0%';const grid=$('#overview-apps');grid.className=apps.length?'app-grid':'app-grid empty-state';grid.innerHTML=apps.length?apps.map(appCard).join(''):'No apps configured yet. Use “Configure app” to begin.';
  ['credential-slug','source-slug','build-slug','brief-slug','store-slug','release-slug'].forEach(id=>{const old=$(`#${id}`).value;$(`#${id}`).innerHTML=optionList(old)});const repo=state.github.factory_repo||'';$('#factory-repo').value=$('#factory-repo').value||repo;$('#bridge-factory-repo').value=$('#bridge-factory-repo').value||repo;
  $('#publish-repo').value=$('#publish-repo').value||repo;$('#gh-dot').classList.toggle('ok',state.github.authenticated);$('#gh-label').textContent=state.github.authenticated?'GitHub connected':state.github.installed?'GitHub sign-in needed':'GitHub CLI required';$('#gh-detail').textContent=state.github.authenticated?(repo||'Ready for configuration'):'See Store access';const cp=state.control_plane||{};$('#control-plane-status').textContent=cp.configured?`Connected to ${cp.url}${cp.openai_configured?' · OpenAI planner ready':' · prompt export only'}`:'Set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY on the Python server.';$('#sync-supabase').disabled=!cp.configured;renderBridgeApps();renderGuide();renderStore();$$('.edit-app').forEach(b=>b.onclick=()=>editApp(b.dataset.slug));}
function renderCapabilities(){const labels={browser:'External browser',camera:'Camera capture',filesystem:'Files & documents',network:'Network status',preferences:'Local preferences',push:'Push notifications',share:'Native sharing'};$('#capabilities').innerHTML=Object.entries(labels).map(([v,l])=>`<label><input type="checkbox" name="capabilities" value="${v}">${l}</label>`).join('')}
function renderBridgeApps(){const source=$('#source-slug').value;const selected=state.apps.find(a=>a.slug===source);const matching=selected?state.apps.filter(a=>a.source.repo===selected.source.repo):state.apps;$('#bridge-apps').innerHTML=matching.length?matching.map(a=>`<label><input type="checkbox" name="slugs" value="${escapeHtml(a.slug)}" checked>${escapeHtml(a.native.display_name)} · ${escapeHtml(a.app_role)}</label>`).join(''):'Configure an app first.'}
function renderGuide(){const checks=[];checks.push({level:state.apps.length?'PASS':'FAIL',label:'Applications configured',detail:state.apps.length?`${state.apps.length} app manifest(s) ready`:'Create at least one application'});checks.push({level:state.github.authenticated?'PASS':'FAIL',label:'GitHub connection',detail:state.github.authenticated?'GitHub CLI authenticated':'Install GitHub CLI and run gh auth login'});for(const app of state.apps){for(const check of app.checks)checks.push({...check,label:`${app.native.display_name}: ${check.label}`})}checks.push({level:'MANUAL',label:'Real-device testing',detail:'Test every role app on physical Android and Apple devices'});checks.push({level:'MANUAL',label:'Production approval',detail:'Review release notes, privacy declarations and staged rollout'});$('#guide-checks').innerHTML=checks.map((c,i)=>`<div class="guide-item ${c.level.toLowerCase()}"><span>${c.level==='PASS'?'✓':c.level==='FAIL'?'!':i+1}</span><div><b>${escapeHtml(c.label)}</b><small>${escapeHtml(c.detail)}</small></div><em>${escapeHtml(c.level)}</em></div>`).join('')}
function renderStore(){const form=$('#store-form');const slug=$('#store-slug').value;const app=state.apps.find(a=>a.slug===slug);if(!form||!app)return;for(const name of storeFields){const input=form.elements[name];if(!input)continue;if(input.type==='checkbox')input.checked=Boolean(app.store[name]);else input.value=app.store[name]??''}const items=[];for(const[k,files]of Object.entries(app.store_assets||{})){if(files.length)items.push(`${k}: ${files.length}`)}$('#asset-summary').innerHTML=items.length?`<b>Saved store artwork</b><span>${escapeHtml(items.join(' · '))}</span>`:'<b>No store artwork saved</b><span>Upload screenshots and graphics below.</span>'}
function editApp(slug){const a=state.apps.find(x=>x.slug===slug);if(!a)return;go('apps');$('#replace').value='true';$('#form-mode').textContent=`Editing ${a.native.display_name}`;$('#slug').value=a.slug;$('#slug').readOnly=true;$('#suite').value=a.suite;$('#app-role').value=a.app_role;$('#display-name').value=a.native.display_name;$('#app-id').value=a.native.ios_bundle_id;$('#repo').value=a.source.repo;$('#source-ref').value=a.source.ref;$('#web-dir').value=a.source.web_dir;$('#package-manager').value=a.source.package_manager;$('#runner').value=a.native.runner;$('#ios-package-manager').value=a.native.ios_package_manager;$$('#capabilities input').forEach(x=>x.checked=a.native.capabilities.includes(x.value));const map={'brand-name':'brand_name','legal-owner':'legal_owner','google-name':'google_developer_name','apple-team':'apple_team_id','apple-app-id':'apple_app_id','support-url':'support_url','privacy-url':'privacy_url','deletion-url':'account_deletion_url','play-track':'play_track'};for(const[id,key]of Object.entries(map))$(`#${id}`).value=a.store[key]||'';toast('Editing existing app. Upload files only when replacing them.')}
function resetApp(){$('#app-form').reset();$('#replace').value='false';$('#slug').readOnly=false;$('#form-mode').textContent='New application';$('#source-ref').value='main';$('#web-dir').value='dist';$('#app-role').value='main';$('#runner').value='github-macos';$('#play-track').value='internal'}
async function load(){busy(true);try{const data=await fetch('/api/state').then(r=>r.json());state=data;renderCapabilities();render();}catch(e){toast(e.message,true)}finally{busy(false)}}
async function submitForm(form,url){busy(true);try{const data=await api(url,{method:'POST',body:new FormData(form)});toast(data.message||'Saved successfully');return data}catch(e){toast(e.message,true);throw e}finally{busy(false)}}
document.addEventListener('DOMContentLoaded',()=>{$$('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.panel));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#source-slug').onchange=renderBridgeApps;$('#store-slug').onchange=renderStore;
  $('#display-name').addEventListener('input',e=>{if($('#replace').value==='true')return;const slug=e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');$('#suite').value=$('#suite').value||slug;$('#slug').value=slug;$('#brand-name').value=e.target.value;$('#google-name').value=e.target.value});
  $('#suggest-id').onclick=()=>{let domain=$('#brand-domain').value.trim().toLowerCase().replace(/^https?:\/\//,'').split('/')[0].replace(/^www\./,'');if(!domain)return toast('Enter the brand domain first.',true);const reversed=domain.split('.').reverse().join('.');const role=$('#app-role').value.trim().toLowerCase().replace(/[^a-z0-9_]/g,'');$('#app-id').value=`${reversed}.${role==='main'||!role?'app':role}`};
  $('#app-form').onsubmit=async e=>{e.preventDefault();try{const data=await submitForm(e.target,'/api/apps');state.apps=data.apps;resetApp();render();go('overview')}catch{}};
  $('#publish-form').onsubmit=async e=>{e.preventDefault();busy(true);const repo=$('#publish-repo').value;try{const data=await api('/api/factory/publish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({factory_repo:repo,message:$('#publish-message').value,create_if_missing:$('#create-repo').checked})});state.github.factory_repo=repo;render();toast(data.message)}catch(err){toast(err.message,true)}finally{busy(false)}};
  $('#credential-form').onsubmit=async e=>{e.preventDefault();const slug=$('#credential-slug').value;if(!slug)return toast('Configure an app first.',true);const repo=$('#factory-repo').value;try{const data=await submitForm(e.target,`/api/apps/${encodeURIComponent(slug)}/credentials`);state.github.factory_repo=repo;e.target.reset();$('#factory-repo').value=repo;render();toast(`${data.configured.length} protected values updated; local fields cleared.`)}catch{}};
  $('#generate-brief').onclick=async()=>{const slug=$('#brief-slug').value;if(!slug)return toast('Configure an app first.',true);busy(true);try{const data=await api(`/api/apps/${encodeURIComponent(slug)}/brief`,{method:'POST'});toast(`Capacitor-ready brief created: ${data.path}`)}catch(e){toast(e.message,true)}finally{busy(false)}};
  $('#generate-plan').onclick=async()=>{const slug=$('#brief-slug').value;if(!slug)return toast('Configure an app first.',true);busy(true);try{const data=await api(`/api/apps/${encodeURIComponent(slug)}/plan`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({goals:$('#planning-goals').value,call_ai:$('#call-openai').checked})});toast(data.plan_path?`AI app plan created: ${data.plan_path}`:`ChatGPT planning prompt created: ${data.prompt_path}`)}catch(e){toast(e.message,true)}finally{busy(false)}};
  $('#sync-supabase').onclick=async()=>{busy(true);try{const data=await api('/api/control-plane/sync',{method:'POST'});toast(data.message)}catch(e){toast(e.message,true)}finally{busy(false)}};
  $('#store-form').onsubmit=async e=>{e.preventDefault();const slug=$('#store-slug').value;if(!slug)return toast('Configure an app first.',true);const payload={};for(const name of storeFields){const input=e.target.elements[name];if(input)payload[name]=input.type==='checkbox'?input.checked:input.value}busy(true);try{const data=await api(`/api/apps/${encodeURIComponent(slug)}/store`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});state.apps=data.apps;render();toast('Store details saved')}catch(err){toast(err.message,true)}finally{busy(false)}};
  $$('.store-assets').forEach(input=>input.onchange=async()=>{const slug=$('#store-slug').value;if(!slug||!input.files.length)return;const body=new FormData();for(const file of input.files)body.append('files',file);busy(true);try{const data=await api(`/api/apps/${encodeURIComponent(slug)}/store-assets/${encodeURIComponent(input.dataset.kind)}`,{method:'POST',body});state.apps=data.apps;renderStore();input.value='';toast(`${data.saved.length} store image(s) saved`)}catch(e){toast(e.message,true)}finally{busy(false)}});
  $('#generate-store-package').onclick=async()=>{const slug=$('#store-slug').value;if(!slug)return toast('Configure an app first.',true);busy(true);try{const data=await api(`/api/apps/${encodeURIComponent(slug)}/store-package`,{method:'POST'});toast(`Submission package created: ${data.path}`)}catch(e){toast(e.message,true)}finally{busy(false)}};
  $('#bridge-form').onsubmit=async e=>{e.preventDefault();const repo=$('#bridge-factory-repo').value;try{const data=await submitForm(e.target,'/api/bridge');e.target.reset();$('#bridge-factory-repo').value=repo;renderBridgeApps();toast(`Bridge installed in ${data.source_repo}; local token field cleared.`)}catch{}};
  $('#build-form').onsubmit=async e=>{e.preventDefault();const slug=$('#build-slug').value;if(!slug)return toast('Configure an app first.',true);const destination=$('#build-submit').value;busy(true);try{const data=await api(`/api/apps/${encodeURIComponent(slug)}/build`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({platform:$('#build-platform').value,submit:destination!=='artifact',metadata:destination==='metadata',factory_repo:state.github.factory_repo})});toast(data.message);setTimeout(refreshRuns,2500)}catch(err){toast(err.message,true)}finally{busy(false)}};
  $('#release-slug').onchange=()=>{$('#release-confirmation').placeholder=`SUBMIT ${$('#release-slug').value}`};
  $('#release-form').onsubmit=async e=>{e.preventDefault();const slug=$('#release-slug').value;if(!slug)return toast('Configure an app first.',true);busy(true);try{const data=await api(`/api/apps/${encodeURIComponent(slug)}/release`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({platform:$('#release-platform').value,tested_build_number:$('#tested-build-number').value,source_sha:$('#release-source-sha').value,qa_notes:$('#release-qa-notes').value,confirmation:$('#release-confirmation').value,factory_repo:state.github.factory_repo})});toast(data.message);e.target.reset()}catch(err){toast(err.message,true)}finally{busy(false)}};
  $('#refresh-runs').onclick=refreshRuns;load()});
async function refreshRuns(){busy(true);try{const data=await api(`/api/runs?repo=${encodeURIComponent(state.github.factory_repo||$('#factory-repo').value)}`);const body=$('#runs-body');body.innerHTML=data.runs.length?data.runs.map(r=>`<tr><td><a href="${escapeHtml(r.url)}" target="_blank" rel="noreferrer">#${r.databaseId}</a><br><small>${escapeHtml(r.displayTitle)}</small></td><td>${escapeHtml(r.headBranch)}</td><td>${new Date(r.createdAt).toLocaleString()}</td><td><span class="run-status ${escapeHtml(r.conclusion||r.status)}">${escapeHtml(r.conclusion||r.status)}</span></td><td>${r.conclusion==='success'?`<button class="text-button download-run" data-run="${r.databaseId}">Download</button>`:'—'}</td></tr>`).join(''):'<tr><td colspan="5" class="empty-cell">No build runs found.</td></tr>';$$('.download-run').forEach(b=>b.onclick=()=>downloadRun(b.dataset.run))}catch(e){toast(e.message,true)}finally{busy(false)}}
async function downloadRun(run){busy(true);try{const data=await api(`/api/runs/${run}/download`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({factory_repo:state.github.factory_repo})});toast(`Output downloaded to ${data.path}`)}catch(e){toast(e.message,true)}finally{busy(false)}}
