-- Compatibility entry point for manual Supabase setup.
--
-- The authoritative schema is versioned in ../supabase/migrations/. Apply it
-- with Lovable Cloud or `supabase db push`; do not create parallel tables.
-- The current model is:
--   organisations -> native_apps -> plans, readiness, listings, build jobs
--                 -> update delivery mappings and release approvals
--
-- The Python service-role key belongs only on the Python server/worker and must
-- never be placed in Lovable browser code or in a VITE_* variable.
